import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { Poppins } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { CartProvider } from './context/CartContext'; // import provider cart

export const metadata: Metadata = {
  title: 'Coffee Time',
  description: 'Generated by suka suka dev',
};

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-poppins',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <CartProvider>
        <html lang="en" className={poppins.variable}>
          <body>{children}</body>
        </html>
      </CartProvider>
    </ClerkProvider>
  );
}
